### ISSUE TITLE
Null Pointer Exception onSensorChanged

### ISSUE THREAD

**Issue by jaffar02** [NachiketaVadera/Flashlight#8]
**Describe the bug**
Upon vibrating the phone app is crashing with the following exception!

**Exception**
```
FATAL EXCEPTION: main
Process: android.nachiketa.flashlight, PID: 13636
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at android.nachiketa.flashlight.Global.changeBackground(Global.java:34)
	at android.nachiketa.flashlight.Global.torchToggle(Global.java:55)
	at android.nachiketa.flashlight.FlashlightShakeToggle.onSensorChanged(FlashlightShakeToggle.java:67)
	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:857)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:181)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Device details**
Android version: 10
Device vendor: Xaomi
Device name: Redmi note 9s

**Comment by rhisav25** [comment]
is the issue resolved? or still there?

**Comment by jaffar02** [comment]
> is the issue resolved? or still there?

Unfortunately yes, though the flashlight turns on & off followed by an immediate app crash.
